const $=(q,r=document)=>r.querySelector(q),$$=(q,r=document)=>[...r.querySelectorAll(q)];
const defaults={muted:false,volume:72,wake:true,glass:55,holo:85,profiles:{authorized:[]}};let settings;try{settings={...defaults,...JSON.parse(localStorage.getItem('visty.settings')||'{}')}}catch{settings={...defaults}}settings.profiles=settings.profiles||{authorized:[]};settings.profiles.authorized=settings.profiles.authorized||[];
const icon={rooms:'<svg viewBox="0 0 24 24"><path d="M3 21V4h14v17M17 10h4v11M7 8h6M7 12h6M7 16h3"/></svg>',light:'<svg viewBox="0 0 24 24"><path d="M9 18h6M10 22h4M8 14a6 6 0 1 1 8 0c-1 1-1 2-1 3H9c0-1 0-2-1-3Z"/></svg>',blind:'<svg viewBox="0 0 24 24"><path d="M4 4h16v16H4ZM4 8h16M4 12h16M4 16h16"/></svg>',plug:'<svg viewBox="0 0 24 24"><path d="M8 3v6M16 3v6M6 8h12v3a6 6 0 0 1-12 0ZM12 17v5"/></svg>',sensor:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="2"/><path d="M8 8a6 6 0 0 0 0 8M16 8a6 6 0 0 1 0 8M5 5a10 10 0 0 0 0 14M19 5a10 10 0 0 1 0 14"/></svg>',climate:'<svg viewBox="0 0 24 24"><path d="M9 15V5a3 3 0 0 1 6 0v10a5 5 0 1 1-6 0ZM12 8h3M12 12h3"/></svg>',lock:'<svg viewBox="0 0 24 24"><rect x="4" y="10" width="16" height="11" rx="3"/><path d="M8 10V7a4 4 0 0 1 8 0v3M12 14v3"/></svg>',shield:'<svg viewBox="0 0 24 24"><path d="M12 3 20 6v6c0 5-3 8-8 10-5-2-8-5-8-10V6Z"/></svg>',voice:'<svg viewBox="0 0 24 24"><path d="M8 10a4 4 0 0 0 8 0V6a4 4 0 0 0-8 0ZM5 10a7 7 0 0 0 14 0M12 17v5"/></svg>',palette:'<svg viewBox="0 0 24 24"><path d="M12 3a9 9 0 0 0 0 18h2a2 2 0 0 0 0-4h-2a2 2 0 0 1 0-4h5a4 4 0 0 0 4-4c0-3-4-6-9-6Z"/></svg>',users:'<svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="4"/><path d="M2 21a7 7 0 0 1 14 0M16 6a3 3 0 0 1 0 6M18 15a5 5 0 0 1 4 5"/></svg>',wave:'<svg viewBox="0 0 24 24"><path d="M3 12h2l2-6 3 12 3-15 3 14 2-5h3"/></svg>'};
const screen=$('#screen'),content=$('#content'),voice=$('#voice');let toastTimer;
function save(){localStorage.setItem('visty.settings',JSON.stringify(settings));apply()}
function apply(){document.documentElement.style.setProperty('--glass',settings.glass/100);document.documentElement.style.setProperty('--holo',settings.holo/100);voice.classList.toggle('muted',settings.muted);$('#voiceStatus').textContent=settings.muted?'MICRÓFONO SILENCIADO':'LISTA PARA ESCUCHAR';$('#voiceHint').textContent=settings.muted?'Mantén 3 s para activar':'Toca para hablar · mantén 3 s para silenciar'}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2200)}function haptic(p=10){navigator.vibrate?.(p)}
function notice(text,svg=icon.wave){return `<div class="notice">${svg}<span>${text}</span></div>`}function card(svg,title,sub,attr='',cls=''){return `<button class="card ${cls}" ${attr}>${svg}<h3>${title}</h3><small>${sub}</small></button>`}
function home(){return notice('Google Home no está conectado. Las habitaciones y dispositivos reales aparecerán después de vincular el servicio.')+`<p class="label">Habitaciones</p><button class="hero" data-sheet="rooms">${icon.rooms}<h3>Habitaciones detectadas</h3><p>Sin conexión · no hay habitaciones disponibles</p></button><p class="label">Controles preparados</p><div class="strip">${[['light','Luces'],['blind','Persianas'],['plug','Enchufes'],['sensor','Sensores'],['climate','Climatización']].map(x=>card(icon[x[0]],x[1],'Sin conexión',`data-sheet="device" data-device="${x[1]}"`,'disabled')).join('')}</div>`}
function scenes(){return notice('Las escenas se cargarán desde Google Home. No se confirma ninguna ejecución sin respuesta real del servicio.')+`<p class="label">Escenas holográficas</p><div class="cards">${card(icon.wave,'Escenas de Google Home','Toca para comprobar','data-scene','gold wide')}</div>`}
function security(){return notice('El acceso al dormitorio requiere siempre autenticación biométrica o PIN. La voz nunca basta para desbloquear.',icon.shield)+`<p class="label">Acceso protegido</p><div class="cards">${card(icon.lock,'Cerradura del dormitorio','Mantén 2 s · autenticación obligatoria','data-bedroom','gold wide hold')}</div>`}
function toggle(k,title,sub,svg=icon.voice){return `<div class="row">${svg}<div><strong>${title}</strong><small>${sub}</small></div><button class="toggle ${settings[k]?'on':''}" data-toggle="${k}" role="switch"><i></i></button></div>`}function range(k,title,svg=icon.palette){return `<div class="row">${svg}<div><strong>${title}</strong><small><b data-value>${settings[k]}</b>%</small></div><input class="range" data-range="${k}" type="range" min="0" max="100" value="${settings[k]}"></div>`}
function config(){let speech=!!(window.SpeechRecognition||window.webkitSpeechRecognition);return `<p class="label">Voz y sonidos</p><div class="group">${range('volume','Volumen general',icon.voice)}${toggle('wake','Activación “Visty / Oye Visty”',settings.wake?'Activa con la app abierta':'Desactivada',icon.wave)}<div class="row">${icon.voice}<div><strong>Reconocimiento de voz</strong><small>${speech?'Disponible en este navegador':'No disponible en este navegador'}</small></div><span class="badge">${speech?'Listo':'Limitado'}</span></div></div><p class="label">Apariencia</p><div class="group">${range('glass','Intensidad Liquid Glass')}${range('holo','Hologramas cian / dorado',icon.wave)}</div><p class="label">Seguridad</p><div class="group"><button class="row" data-auth>${icon.shield}<div><strong>Biometría y PIN</strong><small>WebAuthn y PIN protegido localmente</small></div><span class="badge">Configurar</span></button></div><p class="label">Perfiles de voz</p><div class="group"><button class="row" data-profile="admin">${icon.users}<div><strong>Administrador</strong><small>Acceso completo sujeto a autenticación</small></div><span class="badge">Admin</span></button><button class="row" data-profile="authorized">${icon.users}<div><strong>Usuarios autorizados</strong><small>${settings.profiles.authorized.length?settings.profiles.authorized.length+' configurado(s)':'Ninguno configurado'}</small></div><span class="badge">Gestionar</span></button><button class="row" data-profile="guest">${icon.users}<div><strong>Invitado</strong><small>Toda voz desconocida usa este perfil</small></div><span class="badge">Predeterminado</span></button></div>`}
function openRoute(route){const names={home:'Casa',scenes:'Escenas',security:'Seguridad',settings:'Ajustes'};$('#title').textContent=names[route];content.innerHTML=route==='home'?home():route==='scenes'?scenes():route==='security'?security():config();screen.classList.add('open');screen.setAttribute('aria-hidden','false');$$('.dock button').forEach(b=>b.classList.toggle('active',b.dataset.route===route));wire();haptic()}
function closeRoute(){screen.classList.remove('open');screen.setAttribute('aria-hidden','true');$$('.dock button').forEach(b=>b.classList.remove('active'));closeSheet()}
function wire(){$$('[data-sheet]',content).forEach(b=>b.onclick=()=>openSheet(`<h3>${b.dataset.sheet==='rooms'?'Habitaciones':b.dataset.device}</h3><p class="sub">Sin conexión con Google Home</p>${notice(b.dataset.sheet==='rooms'?'No se inventan habitaciones ni dispositivos. Al vincular Google Home, cada habitación abrirá aquí sus controles flotantes.':'Los controles se habilitan solo después de recibir las capacidades reales del dispositivo.',icon.rooms)}`));$('[data-scene]',content)?.addEventListener('click',()=>$('#process').classList.add('open'));$$('[data-toggle]',content).forEach(b=>b.onclick=()=>{settings[b.dataset.toggle]=!settings[b.dataset.toggle];save();b.classList.toggle('on');b.closest('.row').querySelector('small').textContent=settings[b.dataset.toggle]?'Activa con la app abierta':'Desactivada';toast(settings[b.dataset.toggle]?'Activación por voz preparada':'Activación por voz desactivada');haptic()});$$('[data-range]',content).forEach(r=>r.oninput=()=>{settings[r.dataset.range]=+r.value;r.closest('.row').querySelector('[data-value]').textContent=r.value;save()});$('[data-auth]',content)?.addEventListener('click',authSettings);$$('[data-profile]',content).forEach(b=>b.onclick=()=>profilePanel(b.dataset.profile));const lock=$('[data-bedroom]',content);if(lock)hold(lock,2000,p=>lock.style.setProperty('--lock',p),bedroomAuth)}
function openSheet(html){$('#sheetContent').innerHTML=html;$('#sheet').classList.add('open');$('#shade').classList.add('open');$('#sheet').setAttribute('aria-hidden','false');haptic()}function closeSheet(){$('#sheet').classList.remove('open');$('#shade').classList.remove('open');$('#sheet').setAttribute('aria-hidden','true')}
function hold(el,duration,progress,complete){let raf,start,done=false;el.onpointerdown=e=>{e.preventDefault();done=false;start=performance.now();const tick=t=>{let p=Math.min(100,(t-start)/duration*100);progress(p);if(p>=100){done=true;haptic([25,25,30]);complete()}else raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick)};const up=()=>{cancelAnimationFrame(raf);if(!done)progress(0)};el.onpointerup=up;el.onpointercancel=up;el.onpointerleave=up}
const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b)));async function hash(pin,salt){return b64(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(pin+salt)))}
function authSettings(){let has=localStorage.getItem('visty.pinHash');openSheet(`<h3>Seguridad de ajustes</h3><p class="sub">${has?'PIN configurado':'Configura un PIN alternativo de 4 dígitos'}</p><div class="actions"><button id="setupBio">Configurar biometría / WebAuthn</button><input class="pin" id="pinSetup" inputmode="numeric" maxlength="4" placeholder="••••" aria-label="PIN"><div class="error" id="pinError"></div><button class="gold" id="savePin">${has?'Cambiar PIN':'Guardar PIN'}</button></div>`);$('#savePin').onclick=savePin;$('#setupBio').onclick=registerBio}
async function savePin(){let pin=$('#pinSetup').value;if(!/^\d{4}$/.test(pin)){return $('#pinError').textContent='Introduce exactamente 4 dígitos.'}let salt=b64(crypto.getRandomValues(new Uint8Array(16)));localStorage.setItem('visty.pinSalt',salt);localStorage.setItem('visty.pinHash',await hash(pin,salt));closeSheet();toast('PIN protegido y guardado')}
async function registerBio(){if(!window.PublicKeyCredential)return toast('WebAuthn no está disponible');try{let cred=await navigator.credentials.create({publicKey:{challenge:crypto.getRandomValues(new Uint8Array(32)),rp:{name:'V.I.S.T.Y.'},user:{id:crypto.getRandomValues(new Uint8Array(16)),name:'administrador@visty.local',displayName:'Administrador'},pubKeyCredParams:[{alg:-7,type:'public-key'},{alg:-257,type:'public-key'}],authenticatorSelection:{authenticatorAttachment:'platform',userVerification:'required'},timeout:60000,attestation:'none'}});localStorage.setItem('visty.credentialId',b64(cred.rawId));closeSheet();toast('Biometría configurada')}catch{toast('No se completó la configuración')}}
function profilePanel(type){if(type==='admin')return openSheet(`<h3>Administrador</h3><p class="sub">Perfil principal de V.I.S.T.Y.</p>${notice('Los comandos sensibles siguen requiriendo biometría o PIN. La identificación por voz no sustituye la autenticación.',icon.shield)}`);if(type==='guest')return openSheet(`<h3>Invitado</h3><p class="sub">Perfil seguro predeterminado</p>${notice('Toda voz que no pueda identificarse como autorizada se trata automáticamente como Invitado.',icon.users)}`);openSheet(`<h3>Usuarios autorizados</h3><p class="sub">Etiquetas locales; el reconocimiento biométrico de voz requiere un servicio compatible.</p><div id="profileList">${settings.profiles.authorized.map((n,i)=>`<div class="row"><span class="badge">${i+1}</span><div><strong>${escapeHtml(n)}</strong><small>Autorización preparada</small></div><button class="badge" data-remove="${i}">Quitar</button></div>`).join('')||notice('No hay usuarios autorizados configurados.',icon.users)}</div><div class="actions profile-add"><input class="profile-name" id="profileName" maxlength="28" placeholder="Nombre del usuario"><button id="addProfile">Añadir usuario</button></div>`);$('#addProfile').onclick=()=>{let name=$('#profileName').value.trim();if(!name)return toast('Escribe un nombre');settings.profiles.authorized.push(name);save();profilePanel('authorized')};$$('[data-remove]',$('#sheetContent')).forEach(b=>b.onclick=()=>{settings.profiles.authorized.splice(+b.dataset.remove,1);save();profilePanel('authorized')})}
function escapeHtml(t){return t.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function bedroomAuth(){let bio=localStorage.getItem('visty.credentialId'),pin=localStorage.getItem('visty.pinHash');openSheet(`<h3>Autenticación obligatoria</h3><p class="sub">La voz por sí sola nunca puede desbloquear el dormitorio.</p><div class="actions">${bio?'<button id="authBio">Usar biometría</button>':''}${pin?'<input class="pin" id="pinAuth" inputmode="numeric" maxlength="4" placeholder="••••"><div class="error" id="pinError"></div><button class="gold" id="authPin">Verificar PIN</button>':'<button class="gold" id="goSetup">Configurar PIN en Ajustes</button>'}</div>`);$('#authBio')?.addEventListener('click',verifyBio);$('#authPin')?.addEventListener('click',verifyPin);$('#goSetup')?.addEventListener('click',()=>{closeSheet();openRoute('settings');authSettings()})}
async function verifyBio(){try{let id=Uint8Array.from(atob(localStorage.getItem('visty.credentialId')),c=>c.charCodeAt(0));await navigator.credentials.get({publicKey:{challenge:crypto.getRandomValues(new Uint8Array(32)),allowCredentials:[{id,type:'public-key'}],userVerification:'required',timeout:60000}});authenticated()}catch{toast('Autenticación no completada')}}async function verifyPin(){if(await hash($('#pinAuth').value,localStorage.getItem('visty.pinSalt'))===localStorage.getItem('visty.pinHash'))authenticated();else $('#pinError').textContent='PIN incorrecto.'}function authenticated(){closeSheet();toast('Identidad verificada · cerradura sin conexión')}
$$('[data-route]').forEach(b=>b.onclick=()=>openRoute(b.dataset.route));$('#back').onclick=closeRoute;$('#shade').onclick=closeSheet;$('#cancel').onclick=()=>$('#process').classList.remove('open');
let voiceRaf,started,completed,recognition;
function listen(){if(settings.muted)return toast('Micrófono silenciado');voice.classList.add('listening');$('#voiceStatus').textContent='ESCUCHANDO…';$('#voiceHint').textContent='Habla ahora';haptic();const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Speech){setTimeout(()=>processVoice('Reconocimiento no disponible en este navegador'),1500);return}recognition=new Speech();recognition.lang='es-ES';recognition.interimResults=false;recognition.continuous=false;recognition.maxAlternatives=1;recognition.onresult=e=>processVoice(e.results[0][0].transcript);recognition.onerror=e=>{voice.classList.remove('listening');apply();toast(e.error==='not-allowed'?'Permiso de micrófono denegado':'No se pudo reconocer la voz')};recognition.onend=()=>{if(voice.classList.contains('listening')){voice.classList.remove('listening');apply()}};try{recognition.start()}catch{voice.classList.remove('listening');apply();toast('El micrófono ya está activo')}}
async function processVoice(transcript){
  voice.classList.remove('listening');
  voice.classList.add('processing');
  $('#voiceStatus').textContent='PROCESANDO…';
  $('#voiceHint').textContent=transcript;

  try{
    const response=await fetch('https://visty-brain.lovipabs.workers.dev',{
      method:'POST',
      headers:{'Content-Type':'application/json'},
      body:JSON.stringify({texto:transcript})
    });

    const data=await response.json();

    if(!response.ok || !data.respuesta){
      throw new Error(data.error || 'Error de V.I.S.T.Y.');
    }

    voice.classList.remove('processing');
    apply();

    speechSynthesis.cancel();

    const frase=new SpeechSynthesisUtterance(data.respuesta);
    frase.lang='es-ES';
    frase.rate=1;
    frase.pitch=1;
    frase.volume=settings.volume/100;

    speechSynthesis.speak(frase);

  }catch(error){
    console.error('V.I.S.T.Y.:',error);

    voice.classList.remove('processing');
    apply();

    speechSynthesis.cancel();

    const frase=new SpeechSynthesisUtterance(
      'Ahora mismo no puedo conectar con mi sistema de conversación.'
    );

    frase.lang='es-ES';
    frase.volume=settings.volume/100;

    speechSynthesis.speak(frase);
  }
}
voice.onpointerdown=e=>{e.preventDefault();completed=false;started=performance.now();const tick=t=>{let p=Math.min(100,(t-started)/3000*100);voice.style.setProperty('--hold',p);if(p>=100){completed=true;settings.muted=!settings.muted;save();voice.classList.add('processing');haptic([30,25,40]);setTimeout(()=>voice.classList.remove('processing'),500)}else voiceRaf=requestAnimationFrame(tick)};voiceRaf=requestAnimationFrame(tick)};
voice.onpointerup=()=>{let elapsed=performance.now()-started;cancelAnimationFrame(voiceRaf);voice.style.setProperty('--hold',0);if(completed)return;if(elapsed<=500)listen();else toast('Pulsación cancelada')};voice.onpointercancel=()=>{cancelAnimationFrame(voiceRaf);voice.style.setProperty('--hold',0)};document.addEventListener('contextmenu',e=>{if(e.target.closest('.voice,.hold'))e.preventDefault()});
apply();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
